modLoader="javafml"
loaderVersion="[${forge_version},)"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
displayURL="https://github.com/Anvil-Dev/AnvilCraft"
issueTrackerURL="https://github.com/Anvil-Dev/AnvilCraft/issues"
authors="Gugle,XeKr"
description="""${mod_description}\n\nContributors:\n${contributors}\n\nSupporters:\n${supporters}\n- and more...\n"""
logoFile="pack.png" #optional
#credits="Thanks for this example mod goes to Java"

[[dependencies.${mod_id}]]

   modId="forge"
   mandatory=true #mandatory
   versionRange="[${forge_version},)" #mandatory
   ordering="NONE"
   side="BOTH"

[[dependencies.${mod_id}]]
   modId="minecraft"
   mandatory=true
   versionRange="${minecraft_version}"
   ordering="NONE"
   side="BOTH"
